name: CI/CD Frontend Completo

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build and Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moviecards-java
          path: target/*.jar

  stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java

      - name: Deploy to Stage (Pre-Producci√≥n)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-pre-valbuena'
          publish-profile: ${{ secrets.AZURE_PRE_PUBLISH_PROFILE }}
          package: '*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: stage
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java

      - name: Deploy to Production
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-valbuenab'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'